# Generated by Django 4.1 on 2022-09-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0008_appliedjobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='keyskill',
            new_name='keyskills',
        ),
    ]
